version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "VITE_MSG=Hi Docker! 12346"
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
          